### PR TITLE
[WIP] [ISSUE-334] Migrate Project to latest Gatsby release

### PR DESCRIPTION
**Pull request by azihassan**
This PR upgrades gatsby from v2 to v4, and also upgrades all the packages of the application.

This was done with `CXXFLAGS="--std=c++17" yarn upgrade-interactive --latest` and then selecting everything.

The `CXXFLAGS="--std=c++17"` part was needed on my machine because the setup uses g++ to build node-sass.

Even though I found a package-lock.json file in the project, I used yarn instead of npm because I noticed that the former was called in the project's Github actions. npm is mentioned in package.json though, so we probably need to keep one of them otherwise both the package-lock.json and yarn.lock files would have to be kept up to date.

I also had to call `yarn husky install` after the upgrade to solve the 'error Command "husky-run" not found.' issue.

The upgraded gatsby apparently uses a new webpack version that no longer includes polyfills for nodejs modules, so I replaced path.separator with / to avoid having to polyfill `path`. It was the only mention I found of the `path` module throughout the project, so it's probably safe to remove the `path` dependency altogether.

Also, mdx-js/mdx was kept at v1 to maintain gatsby-plugin-mdx compatibility (https://github.com/gatsbyjs/gatsby/issues/34706#issuecomment-1029716942)

This is a WIP PR, the project runs with `yarn develop` but I haven't tested it yet.

Relevant issue : https://github.com/DevC-Casa/geeksblabla.com/issues/334

### CODE REVIEW

**Comment by azihassan** [comment]
The testimonial section is repeated twice, but this is also the case for geeksblabla.ma

**Comment by azihassan** [comment]
The testimonial section is repeated twice, but this is also the case for geeksblabla.ma

**Comment by azihassan** [comment]
The testimonial section is repeated twice, but this is also the case for geeksblabla.ma

**Comment by yjose** [comment]
@azihassan i think you can upgrade mdx too now https://www.gatsbyjs.com/docs/reference/release-notes/v4.20/

**Comment by azihassan** [comment]
Hmm looks like it's still in RC. Upgrade either way ?

**Comment by yjose** [comment]
yeah go for it

**Pull request closed without merging**
